# Generated by Django 5.1.15 on 2026-08-30 19:01

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=32)),
                ("target_description", models.CharField(max_length=500)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Household",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "org_household_number",
                    models.CharField(db_index=True, max_length=100),
                ),
                ("house_number", models.CharField(blank=True, max_length=100)),
                ("street", models.CharField(blank=True, max_length=255)),
                ("town", models.CharField(blank=True, max_length=255)),
                ("province", models.CharField(blank=True, max_length=255)),
                ("district", models.CharField(blank=True, max_length=255)),
                ("municipality", models.CharField(blank=True, max_length=255)),
                ("ward", models.CharField(blank=True, max_length=255)),
                (
                    "date_registered",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ManyToManyField(
                        blank=True,
                        related_name="assigned_households",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CaseFileChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("intake_form", "Intake Forms"),
                            ("family_care_plan", "Family Care Plans"),
                            ("vital_document", "Vital Documents"),
                            ("process_note", "Process Notes"),
                            ("school_report", "School Visit Reports"),
                            ("referral_form", "Referral Forms"),
                            ("success_story", "Success Stories"),
                            ("monthly_report", "Monthly Reports"),
                        ],
                        max_length=32,
                    ),
                ),
                ("sub_item", models.CharField(blank=True, max_length=255)),
                (
                    "has_evidence",
                    models.CharField(
                        blank=True,
                        choices=[("Yes", "Yes"), ("No", "No"), ("", "Unknown")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Caregiver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("SA ID Number", "SA ID Number"),
                            ("Passport Number", "Passport Number"),
                            ("Permit", "Permit"),
                        ],
                        default="SA ID Number",
                        max_length=32,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "surname",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("known_as", models.CharField(blank=True, max_length=255)),
                (
                    "nationality",
                    models.CharField(default="South African", max_length=255),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=16,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("African", "African"),
                            ("White", "White"),
                            ("Coloured", "Coloured"),
                            ("Indian", "Indian"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("disability", models.BooleanField(default=False)),
                ("disability_description", models.TextField(blank=True)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("surname_confirmed", models.BooleanField(default=False)),
                ("surname_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("id_number_confirmed", models.BooleanField(default=False)),
                ("id_number_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("date_of_birth_confirmed", models.BooleanField(default=False)),
                (
                    "date_of_birth_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Married", "Married"),
                            ("Divorced", "Divorced"),
                            ("Widowed", "Widowed"),
                            ("Single", "Single"),
                            ("Cohabiting", "Cohabiting"),
                            ("Separated", "Separated"),
                        ],
                        max_length=32,
                    ),
                ),
                ("cell_number", models.CharField(blank=True, max_length=64)),
                ("home_language", models.CharField(blank=True, max_length=128)),
                (
                    "headship_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Parent Headed", "Parent Headed"),
                            ("Grand Parent Headed", "Grand Parent Headed"),
                            ("Youth Headed", "Youth Headed"),
                            ("Child Headed", "Child Headed"),
                            ("Relative Headed", "Relative Headed"),
                            ("Other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "date_of_birth_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_number_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surname_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="caregiver",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HouseholdMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[
                            ("SA ID Number", "SA ID Number"),
                            ("Passport Number", "Passport Number"),
                            ("Permit", "Permit"),
                        ],
                        default="SA ID Number",
                        max_length=32,
                    ),
                ),
                (
                    "id_number",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                (
                    "surname",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("known_as", models.CharField(blank=True, max_length=255)),
                (
                    "nationality",
                    models.CharField(default="South African", max_length=255),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "sex",
                    models.CharField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=16,
                    ),
                ),
                (
                    "race",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("African", "African"),
                            ("White", "White"),
                            ("Coloured", "Coloured"),
                            ("Indian", "Indian"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("disability", models.BooleanField(default=False)),
                ("disability_description", models.TextField(blank=True)),
                ("date_joined", models.DateField(default=django.utils.timezone.now)),
                ("surname_confirmed", models.BooleanField(default=False)),
                ("surname_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("id_number_confirmed", models.BooleanField(default=False)),
                ("id_number_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("date_of_birth_confirmed", models.BooleanField(default=False)),
                (
                    "date_of_birth_confirmed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relationship_to_head", models.CharField(blank=True, max_length=255)),
                (
                    "date_of_birth_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.household",
                    ),
                ),
                (
                    "id_number_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "surname_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SupportingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("intake_form", "Intake Forms"),
                            ("family_care_plan", "Family Care Plans"),
                            ("vital_document", "Vital Documents"),
                            ("process_note", "Process Notes"),
                            ("school_report", "School Visit Reports"),
                            ("referral_form", "Referral Forms"),
                            ("success_story", "Success Stories"),
                            ("monthly_report", "Monthly Reports"),
                        ],
                        max_length=32,
                    ),
                ),
                ("file", models.FileField(upload_to=core.models.document_upload_path)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("date_of_document", models.DateField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="core_suppor_content_4e92fe_idx",
                    )
                ],
            },
        ),
    ]
