# Generated by Django 5.1.15 on 2026-08-30 19:29

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caregiver",
            name="date_joined",
            field=models.DateField(default=core.models.today),
        ),
        migrations.AlterField(
            model_name="household",
            name="date_registered",
            field=models.DateField(default=core.models.today),
        ),
        migrations.AlterField(
            model_name="householdmember",
            name="date_joined",
            field=models.DateField(default=core.models.today),
        ),
    ]
