# Generated by Django 5.1.15 on 2026-08-30 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_caregiver_date_joined_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_surname", models.CharField(blank=True, max_length=255)),
                ("client_first_name", models.CharField(blank=True, max_length=255)),
                ("client_id_number", models.CharField(blank=True, max_length=64)),
                ("file_no", models.CharField(blank=True, max_length=100)),
                ("person_engaged_name", models.CharField(blank=True, max_length=255)),
                (
                    "person_engaged_contact",
                    models.CharField(blank=True, max_length=255),
                ),
                ("problem_code", models.CharField(blank=True, max_length=64)),
                ("intervention_code", models.CharField(blank=True, max_length=64)),
                (
                    "type_of_engagement",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Office", "Office"),
                            ("Home", "Home"),
                            ("School", "School"),
                            ("Court", "Court"),
                            ("Telephone", "Telephone"),
                            ("Other", "Other"),
                        ],
                        max_length=16,
                    ),
                ),
                ("purpose_and_what_transpired", models.TextField(blank=True)),
                ("outcome_and_follow_up", models.TextField(blank=True)),
                ("evaluation_reflection", models.TextField(blank=True)),
                ("date_of_next_follow_up", models.DateField(blank=True, null=True)),
                ("ssp_name", models.CharField(blank=True, max_length=255)),
                ("ssp_sacssp_number", models.CharField(blank=True, max_length=64)),
                ("ssp_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="process_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_notes",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
