# Generated by Django 5.1.15 on 2026-08-30 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_processnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="household",
            name="checklist_signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="household",
            name="checklist_signed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="household",
            name="checklist_signed_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="household",
            name="checklist_signed_sacssp",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="Assessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overview_situation", models.TextField(blank=True)),
                ("strengths", models.TextField(blank=True)),
                ("psychosocial_social", models.TextField(blank=True)),
                ("psychosocial_stress", models.TextField(blank=True)),
                ("education", models.TextField(blank=True)),
                ("safety", models.TextField(blank=True)),
                ("health_nutrition", models.TextField(blank=True)),
                ("economic_legal", models.TextField(blank=True)),
                ("assessment_summary", models.TextField(blank=True)),
                ("problem_codes", models.CharField(blank=True, max_length=255)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Emergency", "Emergency (24-48 hours)"),
                            ("High", "High (1 week)"),
                            ("Mild", "Mild (2-3 weeks)"),
                        ],
                        max_length=16,
                    ),
                ),
                ("overall_goal", models.TextField(blank=True)),
                ("client_views", models.TextField(blank=True)),
                ("due_date_evaluation", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
