# Generated by Django 5.1.15 on 2026-08-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_household_checklist_signed_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="OVC Organisation", max_length=255)),
                ("logo", models.FileField(blank=True, null=True, upload_to="org/")),
                ("address", models.CharField(blank=True, max_length=500)),
                ("contact", models.CharField(blank=True, max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="assessment",
            name="plan_rows",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
