# Generated by Django 5.1.15 on 2026-08-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_organisation_assessment_plan_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="version_number",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
