# Generated by Django 5.1.15 on 2026-08-30 23:11

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0006_assessment_version_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login_tagline",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="household",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ServiceDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "beneficiary_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "service_date",
                    models.DateField(db_index=True, default=core.models.today),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("Individual Counselling", "Individual Counselling"),
                            ("Family Counselling", "Family Counselling"),
                            ("Home Visit", "Home Visit"),
                            ("School Visit", "School Visit"),
                            ("Support Group", "Support Group"),
                            ("Referral", "Referral"),
                            ("Material Support", "Material Support"),
                            ("Grant Assistance", "Grant Assistance"),
                            (
                                "ID Documentation Assistance",
                                "ID Documentation Assistance",
                            ),
                            ("HIV Testing Referral", "HIV Testing Referral"),
                            ("Health Check", "Health Check"),
                            ("Educational Support", "Educational Support"),
                            ("Psychosocial Support", "Psychosocial Support"),
                            ("Other", "Other"),
                        ],
                        max_length=64,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "beneficiary_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="delivered_services",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-service_date", "-id"],
                "indexes": [
                    models.Index(
                        fields=["household", "service_date"],
                        name="core_servic_househo_c481d4_idx",
                    )
                ],
            },
        ),
    ]
