# Generated by Django 5.1.15 on 2026-08-31 02:30

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_servicetarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('graduated', 'Graduated'), ('transferred', 'Transferred'), ('lost_to_follow_up', 'Lost to follow-up'), ('closed', 'Closed')], db_index=True, default='open', max_length=32),
        ),
        migrations.AddField(
            model_name='household',
            name='status_changed_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='household',
            name='status_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='enrolled_in_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='grade',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='grant_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='hiv_risk_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='hiv_status',
            field=models.CharField(blank=True, choices=[('unknown', 'Unknown'), ('negative', 'Negative'), ('positive', 'Positive'), ('not_disclosed', 'Not disclosed')], default='unknown', max_length=32),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='hiv_test_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='hiv_test_required',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='last_viral_load',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='last_viral_load_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='on_art',
            field=models.CharField(blank=True, choices=[('na', 'Not applicable'), ('yes', 'On ART'), ('no', 'Not on ART'), ('unknown', 'Unknown')], default='na', max_length=16),
        ),
        migrations.AddField(
            model_name='householdmember',
            name='school_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('services', 'Consent to services'), ('information_sharing', 'Information sharing'), ('photo', 'Photo / media consent')], max_length=32)),
                ('caregiver_name', models.CharField(blank=True, max_length=255)),
                ('caregiver_signed', models.BooleanField(default=False)),
                ('caregiver_signed_date', models.DateField(blank=True, null=True)),
                ('child_name', models.CharField(blank=True, max_length=255)),
                ('child_assent', models.BooleanField(default=False)),
                ('child_assent_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='core.household')),
            ],
            options={
                'ordering': ['-caregiver_signed_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Cow1Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_date', models.DateField(default=core.models.today)),
                ('community_issue', models.TextField(blank=True)),
                ('planned_activities', models.TextField(blank=True)),
                ('stakeholders', models.CharField(blank=True, max_length=500)),
                ('expected_outcome', models.TextField(blank=True)),
                ('ssp_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cow1_plans', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cow1_plans', to='core.household')),
            ],
            options={
                'ordering': ['-plan_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluation_date', models.DateField(default=core.models.today)),
                ('period_from', models.DateField(blank=True, null=True)),
                ('period_to', models.DateField(blank=True, null=True)),
                ('progress_against_plan', models.TextField(blank=True)),
                ('remaining_needs', models.TextField(blank=True)),
                ('recommendation', models.CharField(blank=True, choices=[('continue', 'Continue services'), ('close', 'Close / graduate'), ('refer', 'Refer'), ('transfer', 'Transfer')], max_length=16)),
                ('ssp_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='core.household')),
            ],
            options={
                'ordering': ['-evaluation_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FamilyCarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_goal', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('ssp_name', models.CharField(blank=True, max_length=255)),
                ('caregiver_sign_name', models.CharField(blank=True, max_length=255)),
                ('rows', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_plans', to='core.household')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupWorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(default=core.models.today)),
                ('group_name', models.CharField(blank=True, max_length=255)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('attendees_count', models.PositiveIntegerField(default=0)),
                ('attendees_notes', models.TextField(blank=True)),
                ('session_notes', models.TextField(blank=True)),
                ('outcomes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_sessions', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_sessions', to='core.household')),
            ],
            options={
                'ordering': ['-session_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ProtectionIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(default=core.models.today)),
                ('incident_type', models.CharField(blank=True, choices=[('physical_abuse', 'Physical abuse'), ('sexual_abuse', 'Sexual abuse'), ('neglect', 'Neglect'), ('emotional_abuse', 'Emotional / psychological abuse'), ('exploitation', 'Exploitation'), ('abandonment', 'Abandonment'), ('gbv', 'Gender-based violence'), ('other', 'Other')], max_length=32)),
                ('alleged_perpetrator', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('reported_to', models.CharField(blank=True, max_length=255)),
                ('action_taken', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('referred', 'Referred'), ('closed', 'Closed')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_incidents', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protection_incidents', to='core.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protection_incidents', to='core.householdmember')),
            ],
            options={
                'ordering': ['-incident_date', '-id'],
            },
        ),
    ]
