# Generated by Django 5.1.15 on 2026-08-31 03:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0009_casefile_records_and_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='attached_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='supportingdocument',
            name='parent_kind',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['household', 'surname'], name='core_househ_househo_c51bfb_idx'),
        ),
        migrations.AddIndex(
            model_name='householdmember',
            index=models.Index(fields=['household', 'id_number'], name='core_househ_househo_7e88d5_idx'),
        ),
        migrations.AddIndex(
            model_name='supportingdocument',
            index=models.Index(fields=['-uploaded_at'], name='core_suppor_uploade_6ad789_idx'),
        ),
    ]
