# Generated by Django 5.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_id_number_digits'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('sassa', 'SASSA'), ('clinic', 'Clinic / hospital'), ('school', 'School'), ('police', 'SAPS / police'), ('dsd', 'DSD / social work'), ('home_affairs', 'Home Affairs'), ('ngo', 'Partner NGO'), ('other', 'Other')], default='other', max_length=32)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=64)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('is_training', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('agency_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(choices=[('grant', 'Social grant (CSG / FCG / CDG)'), ('hiv_test', 'HIV testing'), ('art', 'ART / chronic care'), ('school', 'School enrolment or support'), ('birth_cert', 'Birth certificate / ID'), ('protection', 'Child protection / SAPS'), ('food', 'Food or material relief'), ('counselling', 'Counselling'), ('other', 'Other')], default='other', max_length=32)),
                ('details', models.TextField(blank=True)),
                ('referred_on', models.DateField(default=core.models.today)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted by partner'), ('completed', 'Completed'), ('declined', 'Declined'), ('no_show', 'No show')], db_index=True, default='sent', max_length=16)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.household')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.householdmember')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='core.partneragency')),
            ],
            options={'ordering': ['-referred_on', '-id']},
        ),
        migrations.CreateModel(
            name='PlannedVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(db_index=True)),
                ('visit_type', models.CharField(choices=[('home', 'Home visit'), ('school', 'School visit'), ('office', 'Office appointment'), ('phone', 'Telephone follow-up'), ('other', 'Other')], default='home', max_length=16)),
                ('purpose', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('done', 'Completed'), ('missed', 'Missed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planned_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_visits', to='core.household')),
            ],
            options={'ordering': ['visit_date', 'id']},
        ),
    ]
