# Generated by Django 5.1

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_referrals_visits_partners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caregiver',
            name='user',
            field=models.OneToOneField(
                blank=True,
                help_text='Optional login so this household caregiver can view their own file.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='household_caregiver',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
