# Generated by Django 5.1.15 on 2026-09-01 08:52

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_caregiver_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(default='Sebueng Itumeleng', max_length=255),
        ),
        migrations.CreateModel(
            name='ScanIntakeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('confirmed', 'Confirmed'), ('discarded', 'Discarded')], db_index=True, default='pending', max_length=16)),
                ('ocr_engine', models.CharField(blank=True, max_length=32)),
                ('handwriting_warning', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_intake_jobs', to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_intake_jobs', to='core.household')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ScanIntakePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to=core.models.scan_page_upload_path)),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('form_type', models.CharField(blank=True, default='unknown', max_length=64)),
                ('form_confidence', models.FloatField(default=0)),
                ('ocr_text', models.TextField(blank=True)),
                ('ocr_confidence', models.FloatField(default=0)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='core.scanintakejob')),
            ],
            options={
                'ordering': ['index', 'id'],
            },
        ),
    ]
