# Generated by Django 5.1.15 on 2026-09-05 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_scanpage_form_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportingdocument',
            name='sub_item',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
