# Generated by Django 5.1.15 on 2026-09-05 15:20

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_supportingdocument_sub_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportingdocument',
            name='file',
            field=models.FileField(max_length=500, upload_to=core.models.document_upload_path),
        ),
    ]
